image: payneteasy/jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository"
  TZ: "Europe/Moscow"

cache:
  paths:
    - .m2/repository

stages:
  - test
  - release

test:
  stage: test
  script:
    - ./mvnw test
  artifacts:
    when: always
    reports:
      junit:
        - "*/target/surefire-reports/TEST-*.xml"

release:
  stage: release
  only:
    - tags
  script:
    - ./mvnw versions:set -DnewVersion=${CI_COMMIT_REF_NAME}
    - ./mvnw test
    - ./mvnw package deploy
